spring:
  codec:
    max-in-memory-size: 10MB
  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://spring-auth-api.vault.azure.net/
  r2dbc:
    url: ${datasource-connectString}
jwt:
  key: ${jwt-key}
  expires-in: 3600
  refresh-expires-in: 604800
discord:
  base-url: https://discord.com/api/v10
  grant-url: ${discord.base-url}/oauth2/token
  authorize-url: ${discord.base-url}/oauth2/authorize
  client-id: ${discord-clientId}
  client-secret: ${discord-clientSecret}
  basic-auth: ${discord-basicAuth}
  scope: identify