spring:
  codec:
    max-in-memory-size: 10MB
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: https://spring-auth-api.vault.azure.net/
  datasource:
    url: ${spring-datasource-url}
    username: ${spring-datasource-username} <username>
    password: ${spring-datasource-password} <password>
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
jwt:
  key: ${jwt-key}
discord:
  base-url: https://discord.com/api/v10
  grant-url: ${discord.base-url}/oauth2/token
  authorize-url: ${discord.base-url}/oauth2/authorize
  client-id: ${discord-clientId]
  client-secret: ${discord-clientSecret}
  basic-auth: ${discord-basicAuth}
  scope: "identify"